fixbib:
	./fixbib.sh

opt:
	sed -i -e "s:^\([[:space:]]*\)url =:\1OPTurl =:g" *.bib
	sed -i -e "s:^\([[:space:]]*\)issn =:\1OPTissn =:g" *.bib
	sed -i -e "s:^\([[:space:]]*\)isbn =:\1OPTisbn =:g" *.bib
