#!/bin/sh

sed '
{
s/\\IeC //g
s/{\\CYRA }/А/g
s/{\\CYRB }/Б/g
s/{\\CYRV }/В/g
s/{\\CYRG }/Г/g
s/{\\CYRD }/Д/g
s/{\\CYRE }/Е/g
s/{\\CYRYO }/Ё/g
s/{\\CYRZH }/Ж/g
s/{\\CYRZ }/З/g
s/{\\CYRI }/И/g
s/{\\CYRISHRT }/Й/g
s/{\\CYRK }/К/g
s/{\\CYRL }/Л/g
s/{\\CYRM }/М/g
s/{\\CYRN }/Н/g
s/{\\CYRO }/О/g
s/{\\CYRP }/П/g
s/{\\CYRR }/Р/g
s/{\\CYRS }/С/g
s/{\\CYRT }/Т/g
s/{\\CYRU }/У/g
s/{\\CYRF }/Ф/g
s/{\\CYRH }/Х/g
s/{\\CYRC }/Ц/g
s/{\\CYRCH }/Ч/g
s/{\\CYRSH }/Ш/g
s/{\\CYRSHCH }/Щ/g
s/{\\CYRHRDSN }/Ъ/g
s/{\\CYRERY }/Ы/g
s/{\\CYRSFTSN }/Ь/g
s/{\\CYREREV }/Э/g
s/{\\CYRYU }/Ю/g
s/{\\CYRYA }/Я/g
s/{\\cyra }/а/g
s/{\\cyrb }/б/g
s/{\\cyrv }/в/g
s/{\\cyrg }/г/g
s/{\\cyrd }/д/g
s/{\\cyre }/е/g
s/{\\cyryo }/ё/g
s/{\\cyrzh }/ж/g
s/{\\cyrz }/з/g
s/{\\cyri }/и/g
s/{\\cyrishrt }/й/g
s/{\\cyrk }/к/g
s/{\\cyrl }/л/g
s/{\\cyrm }/м/g
s/{\\cyrn }/н/g
s/{\\cyro }/о/g
s/{\\cyrp }/п/g
s/{\\cyrr }/р/g
s/{\\cyrs }/с/g
s/{\\cyrt }/т/g
s/{\\cyru }/у/g
s/{\\cyrf }/ф/g
s/{\\cyrh }/х/g
s/{\\cyrc }/ц/g
s/{\\cyrch }/ч/g
s/{\\cyrsh }/ш/g
s/{\\cyrshch }/щ/g
s/{\\cyrhrdsn }/ъ/g
s/{\\cyrery }/ы/g
s/{\\cyrsftsn }/ь/g
s/{\\cyrerev }/э/g
s/{\\cyryu }/ю/g
s/{\\cyrya }/я/g
s/\\CYRA/А/g
s/\\CYRB/Б/g
s/\\CYRV/В/g
s/\\CYRG/Г/g
s/\\CYRD/Д/g
s/\\CYRE/Е/g
s/\\CYRYO/Ё/g
s/\\CYRZH/Ж/g
s/\\CYRZ/З/g
s/\\CYRI/И/g
s/\\CYRISHRT/Й/g
s/\\CYRK/К/g
s/\\CYRL/Л/g
s/\\CYRM/М/g
s/\\CYRN/Н/g
s/\\CYRO/О/g
s/\\CYRP/П/g
s/\\CYRR/Р/g
s/\\CYRS/С/g
s/\\CYRT/Т/g
s/\\CYRU/У/g
s/\\CYRF/Ф/g
s/\\CYRH/Х/g
s/\\CYRC/Ц/g
s/\\CYRCH/Ч/g
s/\\CYRSHCH/Щ/g
s/\\CYRSH/Ш/g
s/\\CYRHRDSN/Ъ/g
s/\\CYRERY/Ы/g
s/\\CYRSFTSN/Ь/g
s/\\CYREREV/Э/g
s/\\CYRYU/Ю/g
s/\\CYRYA/Я/g
s/\\cyra/а/g
s/\\cyrb/б/g
s/\\cyrv/в/g
s/\\cyrg/г/g
s/\\cyrd/д/g
s/\\cyre/е/g
s/\\cyryo/ё/g
s/\\cyrzh/ж/g
s/\\cyrz/з/g
s/\\cyri/и/g
s/\\cyrishrt/й/g
s/\\cyrk/к/g
s/\\cyrl/л/g
s/\\cyrm/м/g
s/\\cyrn/н/g
s/\\cyro/о/g
s/\\cyrp/п/g
s/\\cyrr/р/g
s/\\cyrs/с/g
s/\\cyrt/т/g
s/\\cyru/у/g
s/\\cyrf/ф/g
s/\\cyrh/х/g
s/\\cyrc/ц/g
s/\\cyrch/ч/g
s/\\cyrshch/щ/g
s/\\cyrsh/ш/g
s/\\cyrhrdsn/ъ/g
s/\\cyrery/ы/g
s/\\cyrsftsn/ь/g
s/\\cyrerev/э/g
s/\\cyryu/ю/g
s/\\cyrya/я/g
}
' $1
