#!/bin/sh

FILE=default.titlelist

if [ -f ${FILE}.tex ]
then
    sed -i -e 's/\\T 2A/\\IeC/g' ${FILE}.tex
#    sed -i -e 's:\\unhbox \\voidb@x \\penalty \\@M \\tmspace +\\thinmuskip {.1667em}:~:g' \
#	-e 's:\\unhbox \\voidb@x \\penalty \\@M:~:g' \
#	${FILE}.tex
#   latex2rtf
fi

latex $FILE
latex $FILE
latex $FILE

tex4ht $FILE

mk4ht htlatex $FILE "xhtml,word,oofice,charset=utf-8" "symbol/\! -cunihtf -utf8" "-cvalidate"
# mk4ht htlatex $FILE "xhtml,mathml,charset=utf-8" "symbol/\! -cunihtf -utf8" "-cvalidate"

sed -i -e 's:<!--.*-->::g' ${FILE}.html
