#!/bin/bash

CURDIR=`pwd`

PAPER="$CURDIR"/papers/src

ARCEXT="zip 7z rar tar.gz tgz tar.bz2 tar.xz gz bz2 xz"

cd "$CURDIR"/papers/src

for EXT in ${ARCEXT} pdf
do
    find . -name "*_${EXT}" -exec rename _${EXT} .${EXT} "{}" \;
done	   

cd "$CURDIR"
