#!/bin/bash

CURDIR=`pwd`

TEX_DIR="$CURDIR"/tex

mkdir -p "$TEX_DIR"

cd "$CURDIR"/pdf

for i in *.pdf
do
    file_name=`basename "$i" .pdf`

    if [[ -f ${TEX_DIR}/${file_name}.tex ]]
    then
	echo "File ${TEX_DIR}/${file_name}.tex exist. Skipping"
    else
	echo -e "\
{\\selectlanguage{english}
\\input{tex-title/${file_name}}%
\\paperid{${file_name}}%
\\maketitleToc
\\includepdf[pages=1,pagecommand=\\\\thispagestyle{firstpage}]{pdf/${file_name}.pdf}
\\includepdf[pages=2-,pagecommand=\\\\thispagestyle{fancy}]{pdf/${file_name}.pdf}
}\n" >> ${TEX_DIR}/${file_name}.tex
    fi
    cd "$CURDIR"/pdf
done

cd "$CURDIR"
